// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: snakes.proto
package dto;

public interface GamePlayersOrBuilder extends
    // @@protoc_insertion_point(interface_extends:snakes.GamePlayers)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .snakes.GamePlayer players = 1;</code>
   */
  java.util.List<GamePlayer> 
      getPlayersList();
  /**
   * <code>repeated .snakes.GamePlayer players = 1;</code>
   */
  GamePlayer getPlayers(int index);
  /**
   * <code>repeated .snakes.GamePlayer players = 1;</code>
   */
  int getPlayersCount();
  /**
   * <code>repeated .snakes.GamePlayer players = 1;</code>
   */
  java.util.List<? extends GamePlayerOrBuilder> 
      getPlayersOrBuilderList();
  /**
   * <code>repeated .snakes.GamePlayer players = 1;</code>
   */
  GamePlayerOrBuilder getPlayersOrBuilder(
      int index);
}
