// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: snakes.proto
package dto;

public interface GameStateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:snakes.GameState)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int32 state_order = 1;</code>
   */
  boolean hasStateOrder();
  /**
   * <code>required int32 state_order = 1;</code>
   */
  int getStateOrder();

  /**
   * <code>repeated .snakes.GameState.Snake snakes = 2;</code>
   */
  java.util.List<GameState.Snake> 
      getSnakesList();
  /**
   * <code>repeated .snakes.GameState.Snake snakes = 2;</code>
   */
  GameState.Snake getSnakes(int index);
  /**
   * <code>repeated .snakes.GameState.Snake snakes = 2;</code>
   */
  int getSnakesCount();
  /**
   * <code>repeated .snakes.GameState.Snake snakes = 2;</code>
   */
  java.util.List<? extends GameState.SnakeOrBuilder> 
      getSnakesOrBuilderList();
  /**
   * <code>repeated .snakes.GameState.Snake snakes = 2;</code>
   */
  GameState.SnakeOrBuilder getSnakesOrBuilder(
      int index);

  /**
   * <code>repeated .snakes.GameState.Coord foods = 3;</code>
   */
  java.util.List<GameState.Coord> 
      getFoodsList();
  /**
   * <code>repeated .snakes.GameState.Coord foods = 3;</code>
   */
  GameState.Coord getFoods(int index);
  /**
   * <code>repeated .snakes.GameState.Coord foods = 3;</code>
   */
  int getFoodsCount();
  /**
   * <code>repeated .snakes.GameState.Coord foods = 3;</code>
   */
  java.util.List<? extends GameState.CoordOrBuilder> 
      getFoodsOrBuilderList();
  /**
   * <code>repeated .snakes.GameState.Coord foods = 3;</code>
   */
  GameState.CoordOrBuilder getFoodsOrBuilder(
      int index);

  /**
   * <code>required .snakes.GamePlayers players = 4;</code>
   */
  boolean hasPlayers();
  /**
   * <code>required .snakes.GamePlayers players = 4;</code>
   */
  GamePlayers getPlayers();
  /**
   * <code>required .snakes.GamePlayers players = 4;</code>
   */
  GamePlayersOrBuilder getPlayersOrBuilder();

  /**
   * <code>required .snakes.GameConfig config = 5;</code>
   */
  boolean hasConfig();
  /**
   * <code>required .snakes.GameConfig config = 5;</code>
   */
  GameConfig getConfig();
  /**
   * <code>required .snakes.GameConfig config = 5;</code>
   */
  GameConfigOrBuilder getConfigOrBuilder();
}
