// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: snakes.proto
package dto;

public interface GameConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:snakes.GameConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 width = 1 [default = 40];</code>
   */
  boolean hasWidth();
  /**
   * <code>optional int32 width = 1 [default = 40];</code>
   */
  int getWidth();

  /**
   * <code>optional int32 height = 2 [default = 30];</code>
   */
  boolean hasHeight();
  /**
   * <code>optional int32 height = 2 [default = 30];</code>
   */
  int getHeight();

  /**
   * <code>optional int32 food_static = 3 [default = 1];</code>
   */
  boolean hasFoodStatic();
  /**
   * <code>optional int32 food_static = 3 [default = 1];</code>
   */
  int getFoodStatic();

  /**
   * <code>optional float food_per_player = 4 [default = 1];</code>
   */
  boolean hasFoodPerPlayer();
  /**
   * <code>optional float food_per_player = 4 [default = 1];</code>
   */
  float getFoodPerPlayer();

  /**
   * <code>optional int32 state_delay_ms = 5 [default = 1000];</code>
   */
  boolean hasStateDelayMs();
  /**
   * <code>optional int32 state_delay_ms = 5 [default = 1000];</code>
   */
  int getStateDelayMs();

  /**
   * <code>optional float dead_food_prob = 6 [default = 0.1];</code>
   */
  boolean hasDeadFoodProb();
  /**
   * <code>optional float dead_food_prob = 6 [default = 0.1];</code>
   */
  float getDeadFoodProb();

  /**
   * <code>optional int32 ping_delay_ms = 7 [default = 100];</code>
   */
  boolean hasPingDelayMs();
  /**
   * <code>optional int32 ping_delay_ms = 7 [default = 100];</code>
   */
  int getPingDelayMs();

  /**
   * <code>optional int32 node_timeout_ms = 8 [default = 800];</code>
   */
  boolean hasNodeTimeoutMs();
  /**
   * <code>optional int32 node_timeout_ms = 8 [default = 800];</code>
   */
  int getNodeTimeoutMs();
}
