// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: snakes.proto
package dto;

/**
 * Protobuf enum {@code snakes.NodeRole}
 */
public enum NodeRole
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>NORMAL = 0;</code>
   */
  NORMAL(0),
  /**
   * <code>MASTER = 1;</code>
   */
  MASTER(1),
  /**
   * <code>DEPUTY = 2;</code>
   */
  DEPUTY(2),
  /**
   * <code>VIEWER = 3;</code>
   */
  VIEWER(3),
  ;

  /**
   * <code>NORMAL = 0;</code>
   */
  public static final int NORMAL_VALUE = 0;
  /**
   * <code>MASTER = 1;</code>
   */
  public static final int MASTER_VALUE = 1;
  /**
   * <code>DEPUTY = 2;</code>
   */
  public static final int DEPUTY_VALUE = 2;
  /**
   * <code>VIEWER = 3;</code>
   */
  public static final int VIEWER_VALUE = 3;


  public final int getNumber() {
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static NodeRole valueOf(int value) {
    return forNumber(value);
  }

  public static NodeRole forNumber(int value) {
    switch (value) {
      case 0: return NORMAL;
      case 1: return MASTER;
      case 2: return DEPUTY;
      case 3: return VIEWER;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<NodeRole>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      NodeRole> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<NodeRole>() {
          public NodeRole findValueByNumber(int number) {
            return NodeRole.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return SnakesProto.getDescriptor()
        .getEnumTypes().get(0);
  }

  private static final NodeRole[] VALUES = values();

  public static NodeRole valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private NodeRole(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:snakes.NodeRole)
}

