// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: snakes.proto
package dto;

/**
 * Protobuf enum {@code snakes.PlayerType}
 */
public enum PlayerType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>HUMAN = 0;</code>
   */
  HUMAN(0),
  /**
   * <code>ROBOT = 1;</code>
   */
  ROBOT(1),
  ;

  /**
   * <code>HUMAN = 0;</code>
   */
  public static final int HUMAN_VALUE = 0;
  /**
   * <code>ROBOT = 1;</code>
   */
  public static final int ROBOT_VALUE = 1;


  public final int getNumber() {
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static PlayerType valueOf(int value) {
    return forNumber(value);
  }

  public static PlayerType forNumber(int value) {
    switch (value) {
      case 0: return HUMAN;
      case 1: return ROBOT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<PlayerType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      PlayerType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<PlayerType>() {
          public PlayerType findValueByNumber(int number) {
            return PlayerType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return SnakesProto.getDescriptor()
        .getEnumTypes().get(1);
  }

  private static final PlayerType[] VALUES = values();

  public static PlayerType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private PlayerType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:snakes.PlayerType)
}

