// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: snakes.proto
package dto;

public final class SnakesProto {
  private SnakesProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_snakes_GamePlayer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_snakes_GamePlayer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_snakes_GameConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_snakes_GameConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_snakes_GamePlayers_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_snakes_GamePlayers_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_snakes_GameState_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_snakes_GameState_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_snakes_GameState_Coord_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_snakes_GameState_Coord_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_snakes_GameState_Snake_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_snakes_GameState_Snake_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_snakes_GameMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_snakes_GameMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_snakes_GameMessage_PingMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_snakes_GameMessage_PingMsg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_snakes_GameMessage_SteerMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_snakes_GameMessage_SteerMsg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_snakes_GameMessage_AckMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_snakes_GameMessage_AckMsg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_snakes_GameMessage_StateMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_snakes_GameMessage_StateMsg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_snakes_GameMessage_AnnouncementMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_snakes_GameMessage_AnnouncementMsg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_snakes_GameMessage_JoinMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_snakes_GameMessage_JoinMsg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_snakes_GameMessage_ErrorMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_snakes_GameMessage_ErrorMsg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_snakes_GameMessage_RoleChangeMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_snakes_GameMessage_RoleChangeMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014snakes.proto\022\006snakes\"\240\001\n\nGamePlayer\022\014\n" +
      "\004name\030\001 \002(\t\022\n\n\002id\030\002 \002(\005\022\022\n\nip_address\030\003 " +
      "\002(\t\022\014\n\004port\030\004 \002(\005\022\036\n\004role\030\005 \002(\0162\020.snakes" +
      ".NodeRole\022\'\n\004type\030\006 \001(\0162\022.snakes.PlayerT" +
      "ype:\005HUMAN\022\r\n\005score\030\007 \002(\005\"\334\001\n\nGameConfig" +
      "\022\021\n\005width\030\001 \001(\005:\00240\022\022\n\006height\030\002 \001(\005:\00230\022" +
      "\026\n\013food_static\030\003 \001(\005:\0011\022\032\n\017food_per_play" +
      "er\030\004 \001(\002:\0011\022\034\n\016state_delay_ms\030\005 \001(\005:\004100" +
      "0\022\033\n\016dead_food_prob\030\006 \001(\002:\0030.1\022\032\n\rping_d" +
      "elay_ms\030\007 \001(\005:\003100\022\034\n\017node_timeout_ms\030\010 ",
      "\001(\005:\003800\"2\n\013GamePlayers\022#\n\007players\030\001 \003(\013" +
      "2\022.snakes.GamePlayer\"\260\003\n\tGameState\022\023\n\013st" +
      "ate_order\030\001 \002(\005\022\'\n\006snakes\030\002 \003(\0132\027.snakes" +
      ".GameState.Snake\022&\n\005foods\030\003 \003(\0132\027.snakes" +
      ".GameState.Coord\022$\n\007players\030\004 \002(\0132\023.snak" +
      "es.GamePlayers\022\"\n\006config\030\005 \002(\0132\022.snakes." +
      "GameConfig\032#\n\005Coord\022\014\n\001x\030\001 \001(\021:\0010\022\014\n\001y\030\002" +
      " \001(\021:\0010\032\315\001\n\005Snake\022\021\n\tplayer_id\030\001 \002(\005\022\'\n\006" +
      "points\030\002 \003(\0132\027.snakes.GameState.Coord\0228\n" +
      "\005state\030\003 \002(\0162\".snakes.GameState.Snake.Sn",
      "akeState:\005ALIVE\022)\n\016head_direction\030\004 \002(\0162" +
      "\021.snakes.Direction\"#\n\nSnakeState\022\t\n\005ALIV" +
      "E\020\000\022\n\n\006ZOMBIE\020\001\"\250\007\n\013GameMessage\022\017\n\007msg_s" +
      "eq\030\001 \002(\003\022\021\n\tsender_id\030\n \001(\005\022\023\n\013receiver_" +
      "id\030\013 \001(\005\022+\n\004ping\030\002 \001(\0132\033.snakes.GameMess" +
      "age.PingMsgH\000\022-\n\005steer\030\003 \001(\0132\034.snakes.Ga" +
      "meMessage.SteerMsgH\000\022)\n\003ack\030\004 \001(\0132\032.snak" +
      "es.GameMessage.AckMsgH\000\022-\n\005state\030\005 \001(\0132\034" +
      ".snakes.GameMessage.StateMsgH\000\022;\n\014announ" +
      "cement\030\006 \001(\0132#.snakes.GameMessage.Announ",
      "cementMsgH\000\022+\n\004join\030\007 \001(\0132\033.snakes.GameM" +
      "essage.JoinMsgH\000\022-\n\005error\030\010 \001(\0132\034.snakes" +
      ".GameMessage.ErrorMsgH\000\0228\n\013role_change\030\t" +
      " \001(\0132!.snakes.GameMessage.RoleChangeMsgH" +
      "\000\032\t\n\007PingMsg\0320\n\010SteerMsg\022$\n\tdirection\030\001 " +
      "\002(\0162\021.snakes.Direction\032\010\n\006AckMsg\032,\n\010Stat" +
      "eMsg\022 \n\005state\030\001 \002(\0132\021.snakes.GameState\032s" +
      "\n\017AnnouncementMsg\022$\n\007players\030\001 \002(\0132\023.sna" +
      "kes.GamePlayers\022\"\n\006config\030\002 \002(\0132\022.snakes" +
      ".GameConfig\022\026\n\010can_join\030\003 \001(\010:\004true\032a\n\007J",
      "oinMsg\022.\n\013player_type\030\001 \001(\0162\022.snakes.Pla" +
      "yerType:\005HUMAN\022\030\n\tonly_view\030\002 \001(\010:\005false" +
      "\022\014\n\004name\030\003 \002(\t\032!\n\010ErrorMsg\022\025\n\rerror_mess" +
      "age\030\001 \002(\t\032_\n\rRoleChangeMsg\022%\n\013sender_rol" +
      "e\030\001 \001(\0162\020.snakes.NodeRole\022\'\n\rreceiver_ro" +
      "le\030\002 \001(\0162\020.snakes.NodeRoleB\006\n\004Type*:\n\010No" +
      "deRole\022\n\n\006NORMAL\020\000\022\n\n\006MASTER\020\001\022\n\n\006DEPUTY" +
      "\020\002\022\n\n\006VIEWER\020\003*\"\n\nPlayerType\022\t\n\005HUMAN\020\000\022" +
      "\t\n\005ROBOT\020\001*2\n\tDirection\022\006\n\002UP\020\001\022\010\n\004DOWN\020" +
      "\002\022\010\n\004LEFT\020\003\022\t\n\005RIGHT\020\004B\021\n\000B\013SnakesProtoP",
      "\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_snakes_GamePlayer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_snakes_GamePlayer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_snakes_GamePlayer_descriptor,
        new java.lang.String[] { "Name", "Id", "IpAddress", "Port", "Role", "Type", "Score", });
    internal_static_snakes_GameConfig_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_snakes_GameConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_snakes_GameConfig_descriptor,
        new java.lang.String[] { "Width", "Height", "FoodStatic", "FoodPerPlayer", "StateDelayMs", "DeadFoodProb", "PingDelayMs", "NodeTimeoutMs", });
    internal_static_snakes_GamePlayers_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_snakes_GamePlayers_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_snakes_GamePlayers_descriptor,
        new java.lang.String[] { "Players", });
    internal_static_snakes_GameState_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_snakes_GameState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_snakes_GameState_descriptor,
        new java.lang.String[] { "StateOrder", "Snakes", "Foods", "Players", "Config", });
    internal_static_snakes_GameState_Coord_descriptor =
      internal_static_snakes_GameState_descriptor.getNestedTypes().get(0);
    internal_static_snakes_GameState_Coord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_snakes_GameState_Coord_descriptor,
        new java.lang.String[] { "X", "Y", });
    internal_static_snakes_GameState_Snake_descriptor =
      internal_static_snakes_GameState_descriptor.getNestedTypes().get(1);
    internal_static_snakes_GameState_Snake_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_snakes_GameState_Snake_descriptor,
        new java.lang.String[] { "PlayerId", "Points", "State", "HeadDirection", });
    internal_static_snakes_GameMessage_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_snakes_GameMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_snakes_GameMessage_descriptor,
        new java.lang.String[] { "MsgSeq", "SenderId", "ReceiverId", "Ping", "Steer", "Ack", "State", "Announcement", "Join", "Error", "RoleChange", "Type", });
    internal_static_snakes_GameMessage_PingMsg_descriptor =
      internal_static_snakes_GameMessage_descriptor.getNestedTypes().get(0);
    internal_static_snakes_GameMessage_PingMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_snakes_GameMessage_PingMsg_descriptor,
        new java.lang.String[] { });
    internal_static_snakes_GameMessage_SteerMsg_descriptor =
      internal_static_snakes_GameMessage_descriptor.getNestedTypes().get(1);
    internal_static_snakes_GameMessage_SteerMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_snakes_GameMessage_SteerMsg_descriptor,
        new java.lang.String[] { "Direction", });
    internal_static_snakes_GameMessage_AckMsg_descriptor =
      internal_static_snakes_GameMessage_descriptor.getNestedTypes().get(2);
    internal_static_snakes_GameMessage_AckMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_snakes_GameMessage_AckMsg_descriptor,
        new java.lang.String[] { });
    internal_static_snakes_GameMessage_StateMsg_descriptor =
      internal_static_snakes_GameMessage_descriptor.getNestedTypes().get(3);
    internal_static_snakes_GameMessage_StateMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_snakes_GameMessage_StateMsg_descriptor,
        new java.lang.String[] { "State", });
    internal_static_snakes_GameMessage_AnnouncementMsg_descriptor =
      internal_static_snakes_GameMessage_descriptor.getNestedTypes().get(4);
    internal_static_snakes_GameMessage_AnnouncementMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_snakes_GameMessage_AnnouncementMsg_descriptor,
        new java.lang.String[] { "Players", "Config", "CanJoin", });
    internal_static_snakes_GameMessage_JoinMsg_descriptor =
      internal_static_snakes_GameMessage_descriptor.getNestedTypes().get(5);
    internal_static_snakes_GameMessage_JoinMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_snakes_GameMessage_JoinMsg_descriptor,
        new java.lang.String[] { "PlayerType", "OnlyView", "Name", });
    internal_static_snakes_GameMessage_ErrorMsg_descriptor =
      internal_static_snakes_GameMessage_descriptor.getNestedTypes().get(6);
    internal_static_snakes_GameMessage_ErrorMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_snakes_GameMessage_ErrorMsg_descriptor,
        new java.lang.String[] { "ErrorMessage", });
    internal_static_snakes_GameMessage_RoleChangeMsg_descriptor =
      internal_static_snakes_GameMessage_descriptor.getNestedTypes().get(7);
    internal_static_snakes_GameMessage_RoleChangeMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_snakes_GameMessage_RoleChangeMsg_descriptor,
        new java.lang.String[] { "SenderRole", "ReceiverRole", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
